# The Docker image that will be used to build your app
image: node:latest

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - ./npm

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - build
#  - test
#  - lint
  - deploy

build-stage:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 1 day

pages:
  stage: deploy
  when: manual
  dependencies:
    - build-stage
  script:
    - rm -rf public
    - cp build/index.html build/404.html
    - ls -a
    - mv build public
    - tree
  artifacts:
    paths:
      - public
  only:
    - main
